logging:
  level:
    root: debug

spring:
  datasource:
    url:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username:
    password:

  servlet:
    multipart:
      max-file-size: -1
      max-request-size: -1

server:
  port: 9090

mybatis:
  type-handlers-package: com.model.common.util.mybatis
  configuration:
    map-underscore-to-camel-case: true

img:
  company:
    uri: /Users/jwlee/Downloads/image/company
    directory:
      uri: /Users/jwlee/Downloads/image/company
  slider:
    uri: /Users/jwlee/Downloads/image/slider
    directory:
      uri: /Users/jwlee/Downloads/image/slider
  item:
    uri: /Users/jwlee/Downloads/image/item
    directory:
      uri: /Users/jwlee/Downloads/image/item

smtp:
  mail:
    host: mail.19341.synology.me
    port: 25
    id: 19341
    password: 108108Jo
    sender.address: 19341@daworld.synology.me